### ISSUE TITLE
Could not find suitable distribution for Requirement.parse('dlr==1.0')

### ISSUE THREAD

**Issue by dujm** [awsdocs/aws-greengrass-developer-guide#8] opened 2019-04-23 09:28 UTC
Hi there,
Could you help me to take a look? Thank you! 

Documentation: 
[Configure Optimized Machine Learning Inference Using the AWS Management Console](https://github.com/awsdocs/aws-greengrass-developer-guide/blob/master/doc_source/ml-dlc-console.md)

Problem Description:
1. Operating system: Raspbian for Raspberry Pi 3B+

2. Problem at Step 2.7 **Install the Neo deep learning runtime**

3. The error I got: 'No local packages or working download links found for dlr==1.0
error: **Could not find suitable distribution for Requirement.parse('dlr==1.0')'**

4. I also tried installation using the below two ways but neither worked. 

  * neo-ai-dlr repo 
https://github.com/neo-ai/neo-ai-dlr/tree/master/install/dlr-1.0-py2.py3-armv7l
  * pip install dlr 
https://pypi.org/project/dlr/

**Comment by rashmise** [comment] 2019-04-25 02:08
Hi, @dujm ! Thank you for submitting this issue. I am currently looking into it and will get back to you as soon as possible.

Thanks!

**Comment by rashmise** [comment] 2019-04-29 17:37
Hi @dujm ! Thank you for your patience. 

Unfortunately, I am having trouble reproducing this error, so I'm unsure as to the cause. I would suggest seeking help at the AWS IoT Greengrass forum (https://forums.aws.amazon.com/forum.jspa?forumID=254), where other users and support may have more familiarity with this problem. 

I will close this issue for now, but please feel free to open a new one if you discover information that can be added to our guide to prevent this error for future users.

Thanks!

**Closed as completed** 2019-04-29 21:03 UTC

**Comment by dujm** [comment] 2019-04-29 21:05
Hi @rashmise! 

Thank you for your time and reply! I will try again or ask for help in the forum.
